### ISSUE TITLE
Should links in chat be clickable?

### ISSUE THREAD

**Issue by bruzzi** [cloudspokes/arena-web#272]
http://www.screencast.com/t/dtpdWDqSU

**Comment by flytoj2ee** [comment]
Is it okay to change the chat area support html?

For example, input &lt;a href="http://topcoder.com" &gt; topcoder &lt; /a &gt;

It'll show the link for topcoder.

**Comment by skyhit** [comment]
no, this will make things complex.  can we simply identify the url pattern, and make it clickable?

**Comment by flytoj2ee** [comment]
It's using html pre tag to show the chat text.

If cannot support html, it cannot handle the links. It'll directly output the html code and doesn't parse and show them.

**Comment by flytoj2ee** [comment]
And it has same issue in https://github.com/cloudspokes/arena-web/issues/274 , how to show the searched text?

**Comment by skyhit** [comment]
so I think we have to avoid using pre tag.

what I mean is we don't need to input html fragment. we need to let the application identify url pattern and format as link style.

**Comment by flytoj2ee** [comment]
In current implementation, I still use the pre tag. Because if we don't use pre tag, it'll very complex to handle and show the html input.
In current implementation, if the user input some text starts with http:// or https://, the application will show the links after the text. Please refer to http://postimg.org/image/f4zvvqt3h/

Is this implementation okay?

**Comment by skyhit** [comment]
no, this looks more wired, what if there are two links?

**Comment by flytoj2ee** [comment]
I found a solution for this issue.

a) While receiving the chat message, split the text by space
b) If the text contain links, populate an array, fro example, ["this", "is", "a", "http://test.com"]
c) In html side, wrap the array item with pre tag, it could show the html in this case.
d) If it's a link, wrap it with a link html.

In above example, the output would be < pre >this< /pre >< pre >  is< /pre >< pre > a< pre > <a>http://test.com</a>

**Comment by skyhit** [comment]
this seems much wired. why we can not use span tag? pre tag makes thing complex.

**Comment by flytoj2ee** [comment]
It could use span tag. But it still needs to split the chat text and construct the text again. 

The reason is that it uses data-ng-bind="chat.text" in angularjs.

To show the html in one line, it needs to change to use data-ng-bind-html="chat.text". But if we change to use data-ng-bind-html, it cannot properly show the chat text which contains html tags.

So it needs to split the chat text, shown the normal text with data-ng-bind, and shown the links with data-ng-bind-html.

**Comment by skyhit** [comment]
hmmm, this makes things complex in order to support links.

**Comment by flytoj2ee** [comment]
Yes, it's the reason why I appended the links at the end of chat text in current implementation.

**Comment by skyhit** [comment]
but appending looks wired.

what do you mean for "To show the html in one line"?

**Comment by flytoj2ee** [comment]
for example, input html tags in chat, it'll show as html if using data-ng-bind-html, it'll show pure text if using data-ng-bind.

**Comment by flytoj2ee** [comment]
how to handle this issue? Split the text and then construct the text again?

**Comment by skyhit** [comment]
I don't have clear solution for this, let's leave this issue aside.

**Comment by mdesiderio** [comment]
This issue was moved to appirio-tech/arena-web#259
