### ISSUE TITLE
Can select Next month Dates and it also created a Layout Issue

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#517]
## Description

Can select Next month Dates and it also created a Layout Issue
## Steps

Go to : http://arena.cloud.topcoder.com:3000
Login as heffan
Click 'Contest Creation Wizard'
In the First Step
Click on the Date (eg :Oct 8th)

Check the Circle
## Expected Result

Must fix the Issue; Must restrict the selection and Must fix the Half circle layout issue
## Actual Result

Can select Next month Dates and it also created a Layout Issue
## Environment

Chrome 37.0.2062.102 m in Windows 7
## Image

![14](https://cloud.githubusercontent.com/assets/4592712/4264786/08f9fc88-3c33-11e4-83c0-8cddd3bb7944.png)
## Bug Hunt

Contest Creation Wizard

**Comment by flytoj2ee** [comment]
I think it's reasonable to allow select the next month, and the "Select Contest Start Date" field shows the correct value.

What's your suggestion?

**Comment by skyhit** [comment]
if you check http://fullcalendar.io/, the days for next month are not cilckable

**Comment by flytoj2ee** [comment]
In my test, the days of next month are clickable in http://fullcalendar.io/ if you change the month to August 2014.

And it has some limit if cannot select next month days, for example, the current date is Oct 31, then it only has Oct 31 is selectable, the other days are all disabled because it cannot create the contest in past days.

**Comment by skyhit** [comment]
yes, it is clickable, but will swith to next month in the screen, can we do the same?

**Comment by skyhit** [comment]
fixed.
