### ISSUE TITLE
'Rating Key' section is not align with others

### ISSUE THREAD

**Issue by sdgun** [cloudspokes/arena-web#646]
## Description

'Rating Key' section is not align with others
## Steps

Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
Register for the contest
Click ENTER
In the 'Chat Room'
Expand the 'Rating Key'
Compare the left side position with Registrants and Who's Here
## Expected Result

Must fix the Issue, Must align with Registrants and Who's Here
## Actual Result

'Rating Key' section is not align with others
## Environment

IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7
## Image

![19](https://cloud.githubusercontent.com/assets/4592712/4349080/525359d2-41a7-11e4-9fb6-3831bfdb6db2.png)
## Bug Hunt

Web Arena QA for 201409 Release

**Comment by ananthhh** [comment]
It is aligned properly.There will be rating icons in the gap mentioned in screenshot. Since those users doesn't have rating, rating icons are missing. If rating icons were present, then it will look like below. Should we increase gap here ?
![image](https://cloud.githubusercontent.com/assets/3583234/4593404/b8020066-5085-11e4-9712-8e674883b741.png)

**Comment by skyhit** [comment]
yes, since the right side, has a lot of empty space.

**Comment by skyhit** [comment]
fixed.
